services:
  cache.favicons_webpack:
    parent: 'cache.system'
    tags:
      - name: cache.pool

  favicons_webpack.cache:
    class: 'Symfony\Component\Cache\Adapter\PhpArrayAdapter'
    factory:
      - 'Symfony\Component\Cache\Adapter\PhpArrayAdapter'
      - 'create'
    arguments:
      - '%kernel.cache_dir%/favicons_webpack.cache.php'
      - '@cache.favicons_webpack'

  BlackForest\Symfony\WebpackEncoreBundle\CacheWarmer\FaviconsCacheWarmer:
    public: false
    arguments:
      $cacheKeys: ~ # Build in the extension.
      $fileLocator: '@file_locator'
      $phpArrayFile: '%kernel.cache_dir%/favicons_webpack.cache.php'
      $fallbackCache: '@cache.favicons_webpack'
    tags:
      - name: kernel.cache_warmer
