services:
  BlackForest\Symfony\WebpackEncoreBundle\Asset\FaviconsCollectionInterface: '@BlackForest\Symfony\WebpackEncoreBundle\Asset\FaviconsCollection'

  BlackForest\Symfony\WebpackEncoreBundle\Asset\FaviconsCollection:
    public: false
    arguments:
      $faviconsCollection: ~ # Build in the extension.

  BlackForest\Symfony\WebpackEncoreBundle\Asset\TagRenderer:
    public: false
    arguments:
      - '@BlackForest\Symfony\WebpackEncoreBundle\Asset\FaviconsCollection'
    tags:
      - name: kernel.reset
        method: reset
